# Generated by Django 3.2.3 on 2021-06-04 14:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210604_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.models.get_image_filename),
        ),
    ]
